'use strict';
const $=id=>document.getElementById(id);
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=rows=>'<table class="data">'+rows.map(([a,b])=>`<tr><td>${esc(a)}</td><td>${esc(b===undefined||b===null||b===''?'—':b)}</td></tr>`).join('')+'</table>';
const section=(name,rows)=>`<h2>${esc(name)}</h2>${table(rows)}`;
let settings={},runtime={},snapshot=null,selected='',catalog=[],busy=false,dirty=false,toastTimer,closed=false;
let previousServerSignature='',history=[],lastSample=null;
async function rpc(method,params={}){if(typeof window.PPP_SESSION!=='string'||window.PPP_SESSION.length!==64)throw Error('本地会话脚本未正确载入');const response=await fetch('/api/rpc',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+window.PPP_SESSION},body:JSON.stringify({id:Date.now(),method,params})});if(response.status===401)throw Error('控制会话已更新，请刷新网页');const data=await response.json();if(!response.ok||!data.ok)throw Error(typeof data.error==='string'?data.error:JSON.stringify(data.error));return data.result;}
function notify(text,error=false){$('status').textContent=text;$('toast').textContent=text;$('toast').style.display='block';$('toast').style.borderColor=error?'#ed7373':'var(--blue)';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',6000);}
async function action(fn){if(busy)return;busy=true;document.body.classList.add('busy');try{await fn();if(!closed)await refresh();}catch(e){notify(e.message,true);}finally{busy=false;document.body.classList.remove('busy');}}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('aside [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelector('main').scrollTop=0;}
function bytes(n){n=Number(n)||0;let i=0;while(n>=1024&&i<4){n/=1024;i++;}return (i?n.toFixed(1):n.toFixed(0))+' '+['B','KB','MB','GB','TB'][i];}
function duration(ms){let s=Math.floor((Number(ms)||0)/1000);return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(n=>String(n).padStart(2,'0')).join(':');}
function updateSetting(key,value){settings[key]=value;dirty=true;document.querySelectorAll(`[data-setting="${key}"]`).forEach(input=>{if(input.type==='checkbox')input.checked=!!value;else input.value=value??'';});$('status').textContent='设置已修改，尚未保存';}
function bindInputs(container){container.querySelectorAll('[data-setting]').forEach(input=>{const key=input.dataset.setting;if(input.type==='checkbox')input.checked=!!settings[key];else input.value=settings[key]??'';input.addEventListener('input',()=>updateSetting(key,input.type==='checkbox'?input.checked:input.value));});}
// Labels, explanations and CLI names follow the C++ core and egui configuration schema.
const groups=[['核心启动',[
 ['working_dir','工作目录','','相对路径以此目录为起点，例如 ./servers/vds.json。'],
 ['log_file','核心日志','--log-file=<path>','核心运行日志保存位置，可使用相对路径或绝对路径。'],
 ['log_level','日志级别','--log-level=none|error|warn|info|debug','控制日志详细程度。','select:none,error,warn,info,debug']]],
 ['AI / API 控制',[
 ['web_port','网页监听端口','--port=<port>','默认 19999；保存后下次启动网页控制端生效，端口冲突时自动选择空闲端口。','number'],
 ]],
 ['启动命令界面',[
 ['mode','启动模式','--mode=client|proxy|server','client 使用 TUN，proxy 仅代理，server 为服务端。','select:client,proxy,server'],
 ['config_path','配置文件','--config=<path>','启动时加载的 JSON 配置，例如 ./servers/vds.json。'],
 ['server_dir','服务器目录','--server-dir=<directory>','扫描此目录中的 JSON 文件并显示在服务器列表。'],
 ['dns','DNS','--dns=<ip-list>','多个地址以逗号分隔，例如 1.1.1.1,8.8.8.8；留空使用核心默认值。'],
 ['auto_restart','自动重启间隔','--auto-restart=<seconds>','核心运行指定秒数后重启；0 或留空关闭。','number'],
 ['firewall_rules','防火墙规则','--firewall-rules=<path>','仅服务端模式使用的规则文件。']]],
 ['TUN 与传输',[
 ['tun_ip','TUN IPv4','--tun-ip=<ip>','虚拟网卡使用的 IPv4 地址。'],['tun_gw','TUN 网关','--tun-gw=<ip>','虚拟网络的网关地址。'],
 ['tun_mask','子网掩码','--tun-mask=<bits>','IPv4 子网前缀长度，例如 24。'],['nic','物理网卡','--nic=<interface>','实际网卡名称；留空自动选择。'],['ngw','物理网关','--ngw=<ip>','实际网络默认网关；留空自动探测。'],
 ['tun','TUN 名称','--tun=<name>','虚拟网卡名称；留空使用平台默认值。'],['tun_driver','驱动','--tun-driver=auto|wintun|tap','Windows 虚拟网卡驱动。','select:,auto,wintun,tap'],
 ['tcp_ip_cc','TCP/IP 栈','--lwip=yes|no','lwIP 对应 yes，ctcp 对应 no；auto 不传此参数。','select:auto,lwip,ctcp'],
 ['tun_mux','MUX 通道','--tun-mux=<connections>','复用的并行传输通道数量；0 关闭。','number'],
 ['tun_mux_acceleration','MUX 加速','--tun-mux-acceleration=0|1|2|3','0 关闭，1 远端，2 本地，3 两端加速。','select:,0,1,2,3'],
 ['link_restart','链路重启阈值','--link-restart=<次数>','主出口连续连接失败达到 N 次后重启；连接成功清零，0 关闭。','number'],
 ['tun_lease_time','DHCP 租期','--tun-lease-time-in-seconds=<sec>','Windows DHCP 租期，单位为秒。','number']]],
 ['代理与旁路',[
 ['proxy_http_port','HTTP 端口','--proxy-http-port=<port>','本地 HTTP 代理端口；留空跟随配置，0 关闭。','number'],['proxy_socks_port','SOCKS 端口','--proxy-socks-port=<port>','本地 SOCKS 代理端口；留空跟随配置，0 关闭。','number'],
 ['bypass_ngw','IPv4 旁路网关','--bypass-ngw=<ip>','绕过隧道的 IPv4 流量使用此网关。'],['bypass_ngw6','IPv6 旁路网关','--bypass-ngw6=<ip>','绕过隧道的 IPv6 流量使用此网关；留空使用核心默认值。']]]];
const toggles=[['tun_host','TUN Host','--tun-host=yes|no','允许核心接管主机网络。'],['tun_vnet','TUN VNet','--tun-vnet=yes|no','启用虚拟网卡数据面与子网转发。'],['tun_static','静态 UDP','--tun-static=yes|no','启用当前出口配置中的 udp.static 通道。'],['tun_flash','QoS 标记','--tun-flash=yes|no','为隧道流量设置默认 IP QoS/TOS 标记。'],['block_quic','屏蔽 UDP/443','--block-quic=yes|no','丢弃客户端 TUN 发往 UDP/443 的流量；是否回退 TCP 由应用决定。'],['rt','实时调度','--rt=yes|no','核心实时调度模式；关闭后可能降低 CPU 占用。']];
function field([key,label,command,note,type='text']){const attrs=`data-setting="${key}" aria-label="${label}"`;let input=type.startsWith('select:')?`<select ${attrs}>${type.slice(7).split(',').map(v=>`<option value="${v}">${v||'默认'}</option>`).join('')}</select>`:`<input ${attrs} type="${type}" ${type==='number'?'min="0"':''}>`;return `<span>${label}</span><div class="field-entry">${input}<div class="field-note">${command?esc('{'+command+'}')+' ':''}${esc(note)}</div></div>`;}
function renderSettings(){
 $('settings-fields').innerHTML=groups.map(([name,rows])=>`<h2>${name}</h2><div class="fields">${rows.map(field).join('')}</div>${name==='TUN 与传输'?`<div class="checks settings-checks">${toggles.map(([key,label,cmd,note])=>`<div><label><input type="checkbox" data-setting="${key}">${label}</label><div class="field-note">${esc('{'+cmd+'} '+note)}</div></div>`).join('')}</div>`:''}`).join('');
 bindInputs($('settings'));bindInputs($('overview'));renderRoutes();
}
const routeDefinitions={ip:[['bypass_file','IPv4','--bypass=<path>','IPv4 分流列表。'],['bypass6_file','IPv6','--bypass6=<path>','IPv6 分流列表。'],['dns_rules_file','DNS rules','--dns-rules=<path>','DNS 分流规则。']],geo:[['geo_rules_file','GEO rules','--geo-rules=<path>','GEO 分流规则。'],['geosite_file','GeoSite','--geosite=<path>','域名分类数据库。'],['geoip_file','GeoIP','--geoip=<path>','IP 分类数据库。']]};
let pathVersion=0;
function renderRoutes(){const mode=settings.bypass_mode||'no';document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===mode));const rows=routeDefinitions[mode];$('route-fields').innerHTML=rows?`<h2>${mode==='ip'?'IP':'GEO'} 分流文件</h2><div class="note">支持 ./ 当前目录、../ 上级目录或绝对路径；基于工作目录 ${esc(settings.working_dir)}。</div><div class="fields">${rows.map(([key,label,cmd,note])=>`<span>${label}</span><div class="path-block"><div class="filefield"><input aria-label="${label} 文件路径" data-setting="${key}"><button data-relative="${key}" title="作为工作目录下的相对路径">./</button></div><div class="field-note">${esc('{'+cmd+'} '+note)}</div><div id="path-${key}" class="path-detail">检查中…</div></div>`).join('')}</div>`:'<h2>关闭用户分流</h2><div class="note">不加载用户 IP / GEO 规则，保留核心运行所需的必要路由。</div>';
 bindInputs($('route-fields'));$('route-fields').querySelectorAll('input').forEach(i=>i.addEventListener('change',checkPaths));$('route-fields').querySelectorAll('[data-relative]').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.relative,v=settings[key]||'';if(!/^(?:\.\.?[\\/]|[a-z]:|[\\/])/i.test(v))updateSetting(key,'./'+v);checkPaths();}));checkPaths();}
async function checkPaths(){const version=++pathVersion,rows=routeDefinitions[settings.bypass_mode];if(!rows)return;try{const result=await rpc('host.paths',{paths:rows.map(([k])=>settings[k]||'')});if(version!==pathVersion)return;rows.forEach(([key],i)=>{const e=$('path-'+key);if(e)e.innerHTML=`<span class="${result[i].exists?'green':'yellow'}">${result[i].exists?'已找到':'文件不存在'}</span> · ${esc(result[i].path)}`;});}catch(e){if(version===pathVersion)notify(e.message,true);}}
async function save(){await rpc('host.save',{settings});dirty=false;await commandPreview();await checkPaths();notify('设置已保存，启动参数在重启核心后生效');}
async function commandPreview(){const args=await rpc('host.arguments');$('command-preview').textContent=args.map(a=>/\s/.test(a)?JSON.stringify(a):a).join(' ');}
function interfaces(name,i,n,tun){let rows=[['Name',i.name+(i.description?' ['+i.description+']':'')],['Index',i.index],['Id',i.id],['Interface',[i.ipv4,i.gateway,i.subnet_mask].filter(Boolean).join('  ')]];if(i.ipv6_address||i.ipv6||i.ipv6_gateway)rows.push(['Interface IPv6',[i.ipv6_address||i.ipv6,i.ipv6_gateway,i.ipv6_subnet_mask].filter(Boolean).join('  ')]);if(tun)rows.push(['Aggligator',n.aggligator],['Proxy Interlayer',n.proxy_interlayer],['TCP/IP 栈',n.tcp_ip_cc],['UDP/443 屏蔽',n.block_quic],['Mux State',n.mux_state],['Link State',n.link_state]);(i.dns||[]).forEach((d,j)=>rows.push(['DNS Server '+(j+1),d]));return section(name,rows);}
function renderNetwork(){if(!snapshot){$('network-content').innerHTML='<h2>网络</h2><div class="note">核心未启动，暂无网络信息。</div>';return;}const n=snapshot.network||{};let html='';if(n.mode==='proxy-only')html=section('TUNNEL',[['Mode',n.mode],['Adapter',n.adapter],['Logical IPv4',n.logical_ipv4],['Logical IPv6',n.logical_ipv6],['Tunnel DNS',n.tunnel_dns],['Link State',n.link_state],['Mux State',n.mux_state],['TCP/IP Transport',n.tcp_ip_transport],['DNS Transport',n.dns_transport]]);if(n.tun)html+=interfaces('TUN',n.tun,n,true);if(n.nic)html+=interfaces('NIC',n.nic,n,false);$('network-content').innerHTML=html||'<h2>网络</h2><div class="note">等待接口信息…</div>';}
function visibleOutbounds(all){return all.filter(o=>o.server_menu||(o.tag?.toLowerCase()==='main'&&!all.some(c=>c.server_menu&&c.tag?.toLowerCase()!=='main'&&c.server===o.server&&c.display_name===o.display_name)));}
function renderServers(force=false){const running=runtime.running,rows=running?visibleOutbounds(snapshot?.outbounds||[]):catalog;const signature=JSON.stringify([running,rows,selected]);if(!force&&signature===previousServerSignature)return;previousServerSignature=signature;$('server-title').textContent='服务器';
 $('server-list').innerHTML=rows.length?rows.map((o,i)=>{let key=running?o.tag:o.path,name=running?(o.display_name||o.tag):o.name;return `<div class="server ${selected===key?'chosen':''}" tabindex="0" role="group" aria-label="服务器 ${esc(name)}" data-server="${i}"><div class="server-top"><strong>${esc(name)}</strong>${selected===key?'<span class="blue">已选中</span>':''}${running?`${o.active?'<span class="tag">main</span>':''}${o.route_used?'<span class="tag">split</span>':''}<span class="${o.state===1?'green':'yellow'}">${({0:'connecting',1:'established',2:'reconnecting'})[o.state]||''}</span>`:''}<div class="spacer"></div><span class="${o.probe_reachable?'green':'muted'}">${running?(o.probe_checked?(o.probe_reachable?o.probe_rtt_ms+' ms':'不可达'):'待探测'):''}</span><button data-apply-server="${i}" ${!running&&!o.valid?'disabled':''}>${running?(o.active?'Rank #1':'切换'):'选择并启动'}</button></div><div class="server-bottom"><span>${esc(typeof o.server==='string'?o.server:JSON.stringify(o.server)||o.error||o.path)}</span><div class="spacer"></div><span>${esc(running?(o.current_entry||''):o.path)}</span></div></div>`;}).join(''):'<div class="note">没有可用服务器，请在启动设置中指定配置文件和服务器目录。</div>';
 $('server-list').querySelectorAll('[data-server]').forEach(card=>{const choose=()=>{const o=rows[Number(card.dataset.server)];selected=running?o.tag:o.path;renderServers(true);};card.addEventListener('click',e=>{if(!e.target.closest('button'))choose();});card.addEventListener('keydown',e=>{if(e.target===card&&['Enter',' '].includes(e.key)){e.preventDefault();choose();}});});
 $('server-list').querySelectorAll('[data-apply-server]').forEach(button=>button.addEventListener('click',()=>action(async()=>{const o=rows[Number(button.dataset.applyServer)];if(running){selected=o.tag;const result=await rpc(o.active?'switch_rank1':'switch_server',{tag:o.tag});if(!result.accepted)throw Error('核心未接受此次切换，请检查出口状态');}else{selected=o.path;updateSetting('config_path',o.path);await save();await rpc('host.start');}notify('服务器操作已完成');})));}
function renderCharts(){const s=snapshot||{},t=s.traffic||{};if(runtime.running&&s.monotonic_ms!==lastSample){lastSample=s.monotonic_ms;history.push([Number(t.rx_bytes)||0,Number(t.tx_bytes)||0,Date.now()]);history=history.filter(p=>p[2]>=Date.now()-60000);}if(!runtime.running){history=[];lastSample=null;}
 $('charts').innerHTML=['下载','上传'].map((name,i)=>{let color=i?'#4da2ff':'#35cb85',max=Math.max(1,...history.map(p=>p[i])),points=history.map((p,j)=>`${Math.max(0,800-(Date.now()-p[2])*800/60000)},${105-p[i]/max*90}`).join(' ');return `<div class="chart"><div class="chart-head"><span>${name}</span><span style="color:${color}">${bytes(i?t.tx_bytes:t.rx_bytes)}/s</span></div><svg viewBox="0 0 800 110" preserveAspectRatio="none" aria-label="${name}速率"><path d="M0 25H800 M0 60H800 M0 105H800" stroke="#30363e" stroke-dasharray="4 5"/><polyline points="${points}" fill="none" stroke="${color}" stroke-width="2"/></svg><div class="chart-foot"><span>60s</span><span>峰值 ${bytes(max)}/s</span></div></div>`;}).join('');}
function render(){const s=snapshot||{},t=s.traffic||{},active=(s.outbounds||[]).find(o=>o.active),phase=runtime.running?({connected:'已连接',connecting:'连接中',reconnecting:'重连中'})[s.phase]||s.phase||'运行中':'未启动';$('connection-state').textContent=phase;$('connection-state').className=s.phase==='connected'?'green':'muted';$('admin').textContent=runtime.admin?'管理员':'普通权限';$('uac').hidden=!!runtime.admin;$('core-toggle').textContent=runtime.running?'停止核心':'启动核心';$('settings-path').textContent='设置文件：'+runtime.settings_path;
 $('metrics').innerHTML=[['连接状态',phase,s.phase==='connected'?'green':''],['主出口',active?.display_name||active?.tag||'—','blue'],['运行时间',duration(s.duration_ms),''],['下载速率',bytes(t.rx_bytes)+'/s','green'],['上传速率',bytes(t.tx_bytes)+'/s','blue'],['MUX',runtime.running?`${s.effective_mux_mode||s.mux_state||'—'} · ${s.mux_active_links||0} links`:'—','yellow']].map(([label,value,color])=>`<div class="metric"><div class="label">${label}</div><div class="value ${color}">${esc(value)}</div></div>`).join('');
 $('connection').innerHTML=table([['Server',s.vpn_server||s.server],['GUID',s.guid],['Transport',s.transport],['Bypass Mode',s.bypass_mode],['Http Proxy',s.http_proxy],['Socks Proxy',s.socks_proxy],['Hosting',s.role],['Total',' ']]);$('connection').querySelector('tr:last-child td:last-child').innerHTML=`<span class="green">↓ ${bytes(t.in_bytes)}</span>　<span class="blue">↑ ${bytes(t.out_bytes)}</span>`;
 const api=s.control_api||{};$('api').innerHTML=table([['Web API',runtime.web_url+'/api/rpc'],['Core API',runtime.running?'C++ AI/API · 已连接':'等待核心启动'],['RPC Listen',api.enabled?api.listen:'未启用'],['Authentication',api.authentication||'—'],['Configured Token',api.token_configured?'已配置（隐藏）':'(empty)'],['Clients',api.enabled?`${api.clients||0}/${api.max_clients||1}`:'—']]);
 const routes=s.routes||{},geo=s.geo||{};$('route-summary').innerHTML=table([['当前模式',s.bypass_mode||'未启动'],['旁路网关',routes.bypass_gateway],['GEO 规则数',geo.rule_count??0],['DNS 规则数',routes.dns_rule_count??0]]);$('route-rules').innerHTML=table((geo.split_rules||[]).map(r=>[r.matcher,r.display||r.outbound]));renderNetwork();renderServers();renderCharts();if(runtime.error)$('status').textContent=runtime.error;}
async function refresh(){const wasRunning=runtime.running;runtime=await rpc('host.status');snapshot=runtime.snapshot||null;if(wasRunning&&!runtime.running)catalog=await rpc('host.catalog');render();if($('status').textContent.startsWith('控制端连接失败'))$('status').textContent='已恢复连接本地 C++ 控制端';}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>{updateSetting('bypass_mode',b.dataset.route);renderRoutes();}));
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(async()=>{await save();if(b.dataset.action==='restart'){await rpc('host.restart');notify('核心已按当前设置启动');}})));
$('core-toggle').addEventListener('click',()=>action(async()=>{if(runtime.running)await rpc('host.stop');else{await save();await rpc('host.start');}notify(runtime.running?'核心已停止':'核心已启动');}));
$('refresh-servers').addEventListener('click',()=>action(async()=>{catalog=await rpc('host.catalog');renderServers(true);}));
$('uac').addEventListener('click',()=>action(async()=>{await save();await rpc('host.elevate');closed=true;notify('已请求管理员权限，提升后的控制窗口将重新打开');}));
$('exit').addEventListener('click',()=>action(async()=>{await rpc('host.exit');closed=true;snapshot=null;runtime.running=false;render();notify('控制端已退出，可以关闭网页');}));
document.addEventListener('keydown',e=>{const i=['F1','F2','F3','F4','F5'].indexOf(e.key);if(i>=0){e.preventDefault();go(['overview','network','servers','routes','settings'][i]);}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
async function poll(){if(!busy&&!closed){try{await refresh();}catch(e){$('status').textContent='控制端连接失败：'+e.message;}}if(!closed)setTimeout(poll,1000);}
async function init(){try{settings=await rpc('host.settings');settings.web_port=settings.web_port||'19999';renderSettings();catalog=await rpc('host.catalog');await commandPreview();await refresh();notify('已连接本地 C++ 控制端');poll();}catch(e){notify(e.message,true);}}
init();
